### ISSUE TITLE
Note taking with speech

### ISSUE THREAD

**Issue by ebatuhankaynak** [NinoApp/nino-client#11]

**Comment by selimfirat** [comment]
2 features
- record sound (like markdown)
- record sound and recognize (smart)

https://github.com/zagum/SpeechRecognitionView
https://github.com/gotev/android-speech
https://github.com/Picovoice/cheetah

**Comment by selimfirat** [comment]
Currently working on speech to text feature.

**Comment by selimfirat** [comment]
https://www.stacktips.com/tutorials/android/speech-to-text-in-android

**Comment by selimfirat** [comment]
smart one is already available via Google voice typing button in keyboard.
![Screen Shot 2019-04-26 at 20 14 11](https://user-images.githubusercontent.com/13938178/56824729-f306c600-685f-11e9-9f39-5a7412de3cac.png)

**Comment by selimfirat** [comment]
Probably done. bi baksana emulatörde olmuyo @ebatuhankaynak

**Comment by ebatuhankaynak** [comment]
Works with 2efdce5ad2bb4538e7560d7b06210aa4af9e19fc.
