### ISSUE TITLE
Abby rotation

### ISSUE THREAD

**Issue by ebatuhankaynak** [NinoApp/nino-client#12]
ABBY seems to perform the same even if the image sent is rotated. Check if a correction is done before sending it to abby or abby does this automatically.

If abby ahndles this, there might be an option to close the functionality and make it faster.

**Comment by selimfirat** [comment]
Are there any problem the coordinates returned from abby related to the rotation?

**Comment by selimfirat** [comment]
There is skew correcting option in ABBYY which is not exactly what u say since you may only rotate 90 degrees but abby may correct it like 10 degrees or so. Any ideas?
