### ISSUE TITLE
Speech to intent - Hey nino! I want to take a note...

### ISSUE THREAD

**Issue by selimfirat** [NinoApp/nino-client#13]
Consider integrating https://picovoice.ai/

**Comment by ebatuhankaynak** [comment]
An aar package that they do note mention you need and spend 3 hours trying to figure where it is
https://github.com/Picovoice/Porcupine/tree/master/binding/android

**Comment by ebatuhankaynak** [comment]
http://s7.dosya.tc/server14/wq4aye/porcupine-debug.zip.html

**Comment by ebatuhankaynak** [comment]
https://github.com/Picovoice/Porcupine/blob/master/lib/common/porcupine_params.pv

**Comment by ebatuhankaynak** [comment]
YA NINO DEDIRTMIYOR PARALI :(((
