### ISSUE TITLE
Make photoeditor notification invisible

### ISSUE THREAD

**Issue by selimfirat** [NinoApp/nino-client#19]

**Comment by ebatuhankaynak** [comment]
There seems to be no accessible code in the project that causes the Toast. It is probably in the backend modules that are not accesible

**Comment by selimfirat** [comment]
I couldn't find a way, too. I think we can close this issue. Please close if you do not mind too. If Hamdi hoca mentions it, then we may look further.

**Comment by selimfirat** [comment]
niye ingilizce yazdım lan
