### ISSUE TITLE
A single empty note remains when we delete everything from the settings

### ISSUE THREAD

**Issue by ebatuhankaynak** [NinoApp/nino-client#24]

**Comment by selimfirat** [comment]
is it empty note or empty notebook? notes do not remain as i see but notebooks do.
if notebook, we should not do anything more i believe.

**Comment by ebatuhankaynak** [comment]
Note.

Steps to recreate:
* Add a bunch of notes (that contain a nino pesdk result image)
* Navigate to Settings --> Delete Notes and More --> Delete Everything --> go back with back button
A single empty note remains
Honestly, this is not important and should not be fixed unless it is really easy, let's just let it stay as an issue because why not.

![WhatsApp Image 2019-04-29 at 14 58 21](https://user-images.githubusercontent.com/17289442/56894704-50348e80-6a8f-11e9-94d8-1f26c3b376f7.jpeg)

**Comment by ebatuhankaynak** [comment]
Fun fact, the note is from april 24. So maybe its always the last thing in the note list?

**Comment by selimfirat** [comment]
Could not reproduce with the steps you wrote and I also agree that
"Honestly, this is not important and should not be fixed unless it is really easy, let's just let it stay as an issue because why not."
