### ISSUE TITLE
CameraActivity needs a restoration to make it look less shitty

### ISSUE THREAD

**Issue by ebatuhankaynak** [NinoApp/nino-client#38]
* Determine where the web button should be put in the UI (CreateNoteActivity?)
* Change location/icon of rotate
* Add a back button and preferably make is so that back/home buttons are disabled -completely-, (right now, it starts of being disabled but can be brought back and it kinda stucks there, so its a bug)
* Maybe put better looking buttons
---
* Find a way to show progressbar at every demanding task.
* Extra points if we can somehow printout percentage by gettings callbacks from the server on the progress.

**Comment by selimfirat** [comment]
I may do this task if u OK.

**Comment by ebatuhankaynak** [comment]
Go ahead
