### ISSUE TITLE
PESDK Text alignment

### ISSUE THREAD

**Issue by selimfirat** [NinoApp/nino-client#47]
Texts' alignment should be "justified"

hamdi hoca demişti

**Comment by ebatuhankaynak** [comment]
There is no way we can do this yaaaa

**Comment by selimfirat** [comment]
haydaaa

**Comment by ebatuhankaynak** [comment]
Yani if you can send me the alignment in response I can

**Comment by ebatuhankaynak** [comment]
Xd

**Comment by selimfirat** [comment]
he öyle desene. justified olsun direkt ya çok da şeetmeye gerek yok

**Comment by ebatuhankaynak** [comment]
Left justified Şu an default

**Comment by selimfirat** [comment]
I think it is still not possible.
