### ISSUE TITLE
Features to delete

### ISSUE THREAD

**Issue by ebatuhankaynak** [NinoApp/nino-client#6]
The following features are up for deletion debate:
* "About" section in settings
* "Rate and Review" section in setttings
* Smart Note creator icon (ic_action_camera) on CreateNoteActivity.kt

**Comment by selimfirat** [comment]
* Removed privacy policy button from google sign-in.
* Removed Rate & review in settings.
* Removed About Settings Bottom Sheet and only left "About us".
* Removed Add Checklist shortcut (app üstüne basılı tutulduğunda çıkan).


If needs anything more, please reopen the issue.
